//
// (c) Copyright 2014 DESY, Eugen Wintersberger <eugen.wintersberger@desy.de>
//
// This file is part of python-pnicore.
//
// python-pnicore is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
//
// python-pnicore is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with python-pnicore.  If not, see <http://www.gnu.org/licenses/>.
// ===========================================================================
//
// Created on: Oct 21, 2014
//     Author: Eugen Wintersberger <eugen.wintersberger@desy.de>
//
#pragma once

#include <pni/core/types.hpp>

//----------------------------------------------------------------------------
//!
//! \ingroup pnicore_errors
//! \brief generate translator name
//! 
//! The translator function name is generated by appending "_translator" 
//! to the name of the exception type.
//!
#define ERR_TRANSLATOR_NAME(ETYPE) ETYPE ## _translator

//----------------------------------------------------------------------------
//!
//! \ingroup pnicore_errors
//! \brief generate exception pointer name
//!
//! Eexception pointer names are generated by prepending the C++ exception 
//! type name with "Py" and append "Ptr"
//!
#define ERR_PTR_NAME(ETYPE) Py ## ETYPE ## Ptr

//----------------------------------------------------------------------------
//!
//! \ingroup pnicore_errors
//! \brief generate exception object name
//!
//! The name of an exception object is generated by prepending the C++ 
//! exception type name with "Py".
//! 
#define ERR_OBJ_NAME(ETYPE) Py ## ETYPE

//----------------------------------------------------------------------------
//!
//! \ingroup pnicore_errors
//! \brief generate the error translator
//! 
//! This macro creates the error translator function along with the 
//! corresponding pointer to the exception object.
//!
#define ERR_TRANSLATOR(ETYPE)\
    PyObject *ERR_PTR_NAME(ETYPE) = nullptr;\
    void ERR_TRANSLATOR_NAME(ETYPE)(const ETYPE &error)\
    {\
        assert(ERR_PTR_NAME(ETYPE) != nullptr);\
        object exception(error);\
        PyErr_SetObject(ERR_PTR_NAME(ETYPE),exception.ptr());\
    }

//----------------------------------------------------------------------------
//! 
//! \ingroup pnicore_errors
//! \brief generats the python exception wrapper
//! 
//! Generates the wrapper code for the python exception.
//!
#define ERR_OBJECT_DECL(ETYPE)\
    object ERR_OBJ_NAME(ETYPE) = (\
            class_<ETYPE,bases<exception> >(# ETYPE ));\
    ERR_PTR_NAME(ETYPE) = ERR_OBJ_NAME(ETYPE).ptr();

//----------------------------------------------------------------------------
//!
//! \ingroup pnicore_errors
//! \brief generate registration code
//! 
//! Macro generates the code to register an exception at the module.
//!
#define ERR_REGISTRATION(ETYPE)\
    register_exception_translator<ETYPE>(ERR_TRANSLATOR_NAME(ETYPE)); 

