from distutils import sysconfig
from smod import ProgramVersion
from smod import PythonVersionParser
Import("build_env")


build_env.Append(LIBS=["pniutils"])
build_env.Prepend(LIBS=["pninx"])
build_env.Prepend(LIBPATH=["../src"])

python_version = sysconfig.get_python_version()
python_version = python_version.replace(".","")

build_env.Append(LIBS=["boost_python","boost_python-py"+python_version])
build_env.Append(CPPPATH=[sysconfig.get_python_inc()])

python_sources = ["nx.cpp"]


module = build_env.SharedLibrary("nxh5",python_sources,SHLIBPREFIX="")
build_env.Alias("python",[module])

#installing the python module

python_version = PythonVersionParser().parse()

if python_version < ProgramVersion(2,7,0):
    subpath = "site-packages"
else:
    subpath = "dist-packages"

#assemble installation path
python_install_path = "$LIBINSTPATH"+"/python"+\
                      sysconfig.get_python_version()+\
                      "/"+subpath

python_install = build_env.Install(python_install_path,"pni")
Depends(python_install,module)
build_env.Alias("install",[python_install])

